---
- name: Install firewall package
  hosts: lan
  gather_facts: true
  become: true
  tasks:
     - name: Install Firewalld Pakcges
       yum:
          name: firewalld
          state: present
...
