---
- hosts: lan
  become: true
  become_user: root
  tasks:
    - name: Install 3 package on Server
      yum: name={{item}} state=latest
      with_items:
        - httpd
        - vsftpd
        - firewalld
    - name: After Installing Enable and Start Packages
      service: name={{item}} state=started enabled=true
      with_items:
        - httpd
        - vsftpd
        - firewalld
...



