---
- hosts: lan
  # become: true
  #become_user: root
  tasks:
    - name: Install Packages
      yum: name={{item}} state=latest
      with_items:
        - httpd
        - vsftpd
        - firewalld
    - name: Enable Installed Service
      service: name={{item}} state=started enabled=true
      with_items:
        - httpd
        - vsftpd
        - firewalld       
...
